name             "redis"
maintainer       "Joshua Mervine"
maintainer_email "joshua@mervine.net"
license          "MIT"
description      "Installs/Configures redis from package"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "build-essential"
depends          "apt"
depends          "yum"
